### ISSUE TITLE
[NEW FEAT] French version

### ISSUE THREAD

**Issue by paganaye** [ttsukagoshi/mail-merge-for-gmail#377]
**Is your feature request related to a problem? Please describe.**
I am looking for a mail merge solution in French for Google Sheet / Workspace 
I am going to fork and try to do it myself.
Any help in the meantime would be useful

I am happy to do the translation and check it.

**Comment by ttsukagoshi** [comment]
Hi @paganaye, thank you for your contribution in #378 !
Your translations will appear in the coming weeks, but before they are released, I have to close a conversation with the Google OAuth Verification team. You'll be mentioned in the next release note, so you'll know when it's ready.
Thanks again! 🎊
